name: Deploy Profile App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Lấy source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build & Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tobi1008/profile:latest

      # 4. Prepare VPS Directory
      - name: Create directory on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: 2210
          script: mkdir -p ~/profile-app

      # 5. Copy docker-compose file to VPS
      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: 2210
          source: "docker-compose.prod.yml"
          target: "profile-app"

      # 6. Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: 2210
          script: |
            # Vào thư mục app (scp đã tự tạo thư mục profile-app ở bước trên nếu chưa có)
            cd ~/profile-app
            
            # Đổi tên file vừa copy thành docker-compose.yml chuẩn
            mv docker-compose.prod.yml docker-compose.yml
            
            # Pull image mới nhất
            docker compose pull
            
            # Chạy lại container
            docker compose up -d
            
            # Dọn dẹp image cũ cho nhẹ máy
            docker image prune -f
